# Generated by Django 2.2.6 on 2019-11-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_app', '0006_auto_20191011_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='media/', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='teacherdetails',
            name='teacher_DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacherdetails',
            name='tec_father_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentdetails',
            unique_together={('mail_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='teacherdetails',
            unique_together={('teacher_mail_id',)},
        ),
    ]
